var tableInfo = {
  columns: [
    {
      title: "Full Name",
      width: 100,
      dataIndex: "name",
      key: "name",
      fixed: "left",
    },
    {
      title: "Age",
      width: 100,
      dataIndex: "age",
      key: "age",
      fixed: "left",
    },
    { title: "Column 1", dataIndex: "address", key: "1", width: 150 },
    { title: "Column 2", dataIndex: "address", key: "2", width: 150 },
    { title: "Column 3", dataIndex: "address", key: "3", width: 150 },
    { title: "Column 4", dataIndex: "address", key: "4", width: 150 },
    { title: "Column 5", dataIndex: "address", key: "5", width: 150 },
    { title: "Column 6", dataIndex: "address", key: "6", width: 150 },
    { title: "Column 7", dataIndex: "address", key: "7", width: 150 },
    { title: "Column 8", dataIndex: "address", key: "8" },
    {
      title: "操作",
      key: "operation",
      dataIndex: "operation",
      fixed: "right",
      width: 200,
      name: "编辑",
    },
  ],
  dataSource: [
    { key: 0, name: "Edrward 0", age: 1, address: "London Park no. 0" },
    { key: 1, name: "Edrward 1", age: 2, address: "London Park no. 1" },
    { key: 2, name: "Edrward 2", age: 3, address: "London Park no. 2" },
    { key: 3, name: "Edrward 3", age: 4, address: "London Park no. 3" },
    { key: 4, name: "Edrward 4", age: 5, address: "London Park no. 4" },
    { key: 5, name: "Edrward 5", age: 6, address: "London Park no. 5" },
    { key: 6, name: "Edrward 6", age: 7, address: "London Park no. 6" },
    { key: 7, name: "Edrward 7", age: 8, address: "London Park no. 7" },
    { key: 8, name: "Edrward 8", age: 9, address: "London Park no. 8" },
    { key: 9, name: "Edrward 9", age: 10, address: "London Park no. 9" },
    { key: 10, name: "Edrward 10", age: 11, address: "London Park no. 10" },
    { key: 11, name: "Edrward 11", age: 12, address: "London Park no. 11" },
    { key: 12, name: "Edrward 12", age: 13, address: "London Park no. 12" },
    { key: 13, name: "Edrward 13", age: 14, address: "London Park no. 13" },
    { key: 14, name: "Edrward 14", age: 15, address: "London Park no. 14" },
    { key: 15, name: "Edrward 15", age: 16, address: "London Park no. 15" },
    { key: 16, name: "Edrward 16", age: 17, address: "London Park no. 16" },
    { key: 17, name: "Edrward 17", age: 18, address: "London Park no. 17" },
    { key: 18, name: "Edrward 18", age: 19, address: "London Park no. 18" },
    { key: 19, name: "Edrward 19", age: 20, address: "London Park no. 19" },
    { key: 20, name: "Edrward 20", age: 21, address: "London Park no. 20" },
    { key: 21, name: "Edrward 21", age: 22, address: "London Park no. 21" },
    { key: 22, name: "Edrward 22", age: 23, address: "London Park no. 22" },
    { key: 23, name: "Edrward 23", age: 24, address: "London Park no. 23" },
    { key: 24, name: "Edrward 24", age: 25, address: "London Park no. 24" },
    { key: 25, name: "Edrward 25", age: 26, address: "London Park no. 25" },
    { key: 26, name: "Edrward 26", age: 27, address: "London Park no. 26" },
    { key: 27, name: "Edrward 27", age: 28, address: "London Park no. 27" },
    { key: 28, name: "Edrward 28", age: 29, address: "London Park no. 28" },
    { key: 29, name: "Edrward 29", age: 30, address: "London Park no. 29" },
    { key: 30, name: "Edrward 30", age: 31, address: "London Park no. 30" },
    { key: 31, name: "Edrward 31", age: 32, address: "London Park no. 31" },
    { key: 32, name: "Edrward 32", age: 33, address: "London Park no. 32" },
    { key: 33, name: "Edrward 33", age: 34, address: "London Park no. 33" },
    { key: 34, name: "Edrward 34", age: 35, address: "London Park no. 34" },
    { key: 35, name: "Edrward 35", age: 36, address: "London Park no. 35" },
    { key: 36, name: "Edrward 36", age: 37, address: "London Park no. 36" },
    { key: 37, name: "Edrward 37", age: 38, address: "London Park no. 37" },
    { key: 38, name: "Edrward 38", age: 39, address: "London Park no. 38" },
    { key: 39, name: "Edrward 39", age: 40, address: "London Park no. 39" },
    { key: 40, name: "Edrward 40", age: 41, address: "London Park no. 40" },
    { key: 41, name: "Edrward 41", age: 42, address: "London Park no. 41" },
    { key: 42, name: "Edrward 42", age: 43, address: "London Park no. 42" },
    { key: 43, name: "Edrward 43", age: 44, address: "London Park no. 43" },
    { key: 44, name: "Edrward 44", age: 45, address: "London Park no. 44" },
    { key: 45, name: "Edrward 45", age: 46, address: "London Park no. 45" },
    { key: 46, name: "Edrward 46", age: 47, address: "London Park no. 46" },
    { key: 47, name: "Edrward 47", age: 48, address: "London Park no. 47" },
    { key: 48, name: "Edrward 48", age: 49, address: "London Park no. 48" },
    { key: 49, name: "Edrward 49", age: 50, address: "London Park no. 49" },
    { key: 50, name: "Edrward 50", age: 51, address: "London Park no. 50" },
    { key: 51, name: "Edrward 51", age: 52, address: "London Park no. 51" },
    { key: 52, name: "Edrward 52", age: 53, address: "London Park no. 52" },
    { key: 53, name: "Edrward 53", age: 54, address: "London Park no. 53" },
    { key: 54, name: "Edrward 54", age: 55, address: "London Park no. 54" },
    { key: 55, name: "Edrward 55", age: 56, address: "London Park no. 55" },
    { key: 56, name: "Edrward 56", age: 57, address: "London Park no. 56" },
    { key: 57, name: "Edrward 57", age: 58, address: "London Park no. 57" },
    { key: 58, name: "Edrward 58", age: 59, address: "London Park no. 58" },
  ],
};
